# To execute this docker-compose yml file use docker-compose -f docker-compose-v3.yml up
# Add the -d flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then docker-compose -f docker-compose-v3.yml down
version: "3"
services:
  webdriver:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: webdriver
    restart: always
    depends_on:
      - selenium-hub
    environment:
      - SELENIUM_HUB_HOST=${SELENIUM_HUB}
      - SELENIUM_HUB_PORT=${SELENIUM_HUB_PORT}
      - PRODUCTION=${PRODUCTION}
      - NODE=${NODE}

  chrome:
    image: selenium/node-chrome
    shm_size: 1gb
    restart: always
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  edge:
    image: selenium/node-edge
    shm_size: 1gb
    restart: always
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      
  firefox:
    image: selenium/node-firefox
    shm_size: 1gb
    restart: always
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    restart: always
    environment:
      - SE_SESSION_REQUEST_TIMEOUT=1200
      - SE_SESSION_RETRY_INTERVAL=10
    ports:
      - "4442:4442"
      - "4443:4443"
      - "${SELENIUM_HUB_PORT}:4444"
    volumes:
      - ./config.toml:/opt/selenium/config.toml